version: "3"

services:
  uav_server:
    container_name: uav_server
    image: xevi8x/uav_server
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9090:9090"
      - "9100:9100"
      - "10000-10032:10000-10032"
      - "11000-11032:11000-11032"
    init: true
    volumes:
      - ./data/configs:/UAV/UAV_aggregator/configs
      - ./data/assets:/UAV/UAV_aggregator/assets
      - ./data/logs:/UAV/UAV_aggregator/logs
