name: Publish Docker image

on:
  workflow_dispatch:
  repository_dispatch:
    types: [dependency_update]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: xevi8x/uav_server
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: xevi8x/uav_server:latest
          labels: ${{ steps.meta.outputs.labels }}
